# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import robot_sdk_pb2 as robot__sdk__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_sdk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnableRobot = channel.unary_unary(
                '/humanoid.robot.sdk.v1.RobotControl/EnableRobot',
                request_serializer=robot__sdk__pb2.EnableRobotRequest.SerializeToString,
                response_deserializer=robot__sdk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.DisableRobot = channel.unary_unary(
                '/humanoid.robot.sdk.v1.RobotControl/DisableRobot',
                request_serializer=robot__sdk__pb2.DisableRobotRequest.SerializeToString,
                response_deserializer=robot__sdk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/humanoid.robot.sdk.v1.RobotControl/SetMode',
                request_serializer=robot__sdk__pb2.SetModeRequest.SerializeToString,
                response_deserializer=robot__sdk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.LoadPolicy = channel.unary_unary(
                '/humanoid.robot.sdk.v1.RobotControl/LoadPolicy',
                request_serializer=robot__sdk__pb2.LoadPolicyRequest.SerializeToString,
                response_deserializer=robot__sdk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.StartPolicy = channel.unary_unary(
                '/humanoid.robot.sdk.v1.RobotControl/StartPolicy',
                request_serializer=robot__sdk__pb2.StartPolicyRequest.SerializeToString,
                response_deserializer=robot__sdk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.StopPolicy = channel.unary_unary(
                '/humanoid.robot.sdk.v1.RobotControl/StopPolicy',
                request_serializer=robot__sdk__pb2.StopPolicyRequest.SerializeToString,
                response_deserializer=robot__sdk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.SetVelocityCommand = channel.unary_unary(
                '/humanoid.robot.sdk.v1.RobotControl/SetVelocityCommand',
                request_serializer=robot__sdk__pb2.VelocityCommand.SerializeToString,
                response_deserializer=robot__sdk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.GetRobotStatus = channel.unary_unary(
                '/humanoid.robot.sdk.v1.RobotControl/GetRobotStatus',
                request_serializer=robot__sdk__pb2.GetRobotStatusRequest.SerializeToString,
                response_deserializer=robot__sdk__pb2.RobotStatus.FromString,
                _registered_method=True)


class RobotControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnableRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVelocityCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnableRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableRobot,
                    request_deserializer=robot__sdk__pb2.EnableRobotRequest.FromString,
                    response_serializer=robot__sdk__pb2.CommandReply.SerializeToString,
            ),
            'DisableRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableRobot,
                    request_deserializer=robot__sdk__pb2.DisableRobotRequest.FromString,
                    response_serializer=robot__sdk__pb2.CommandReply.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=robot__sdk__pb2.SetModeRequest.FromString,
                    response_serializer=robot__sdk__pb2.CommandReply.SerializeToString,
            ),
            'LoadPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPolicy,
                    request_deserializer=robot__sdk__pb2.LoadPolicyRequest.FromString,
                    response_serializer=robot__sdk__pb2.CommandReply.SerializeToString,
            ),
            'StartPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPolicy,
                    request_deserializer=robot__sdk__pb2.StartPolicyRequest.FromString,
                    response_serializer=robot__sdk__pb2.CommandReply.SerializeToString,
            ),
            'StopPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPolicy,
                    request_deserializer=robot__sdk__pb2.StopPolicyRequest.FromString,
                    response_serializer=robot__sdk__pb2.CommandReply.SerializeToString,
            ),
            'SetVelocityCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVelocityCommand,
                    request_deserializer=robot__sdk__pb2.VelocityCommand.FromString,
                    response_serializer=robot__sdk__pb2.CommandReply.SerializeToString,
            ),
            'GetRobotStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotStatus,
                    request_deserializer=robot__sdk__pb2.GetRobotStatusRequest.FromString,
                    response_serializer=robot__sdk__pb2.RobotStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'humanoid.robot.sdk.v1.RobotControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('humanoid.robot.sdk.v1.RobotControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnableRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.RobotControl/EnableRobot',
            robot__sdk__pb2.EnableRobotRequest.SerializeToString,
            robot__sdk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.RobotControl/DisableRobot',
            robot__sdk__pb2.DisableRobotRequest.SerializeToString,
            robot__sdk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.RobotControl/SetMode',
            robot__sdk__pb2.SetModeRequest.SerializeToString,
            robot__sdk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.RobotControl/LoadPolicy',
            robot__sdk__pb2.LoadPolicyRequest.SerializeToString,
            robot__sdk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.RobotControl/StartPolicy',
            robot__sdk__pb2.StartPolicyRequest.SerializeToString,
            robot__sdk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.RobotControl/StopPolicy',
            robot__sdk__pb2.StopPolicyRequest.SerializeToString,
            robot__sdk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVelocityCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.RobotControl/SetVelocityCommand',
            robot__sdk__pb2.VelocityCommand.SerializeToString,
            robot__sdk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.RobotControl/GetRobotStatus',
            robot__sdk__pb2.GetRobotStatusRequest.SerializeToString,
            robot__sdk__pb2.RobotStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MotorControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnableMotors = channel.unary_unary(
                '/humanoid.robot.sdk.v1.MotorControl/EnableMotors',
                request_serializer=robot__sdk__pb2.MotorSelection.SerializeToString,
                response_deserializer=robot__sdk__pb2.MotorCommandReply.FromString,
                _registered_method=True)
        self.DisableMotors = channel.unary_unary(
                '/humanoid.robot.sdk.v1.MotorControl/DisableMotors',
                request_serializer=robot__sdk__pb2.MotorSelection.SerializeToString,
                response_deserializer=robot__sdk__pb2.MotorCommandReply.FromString,
                _registered_method=True)
        self.SetMotorVelocity = channel.unary_unary(
                '/humanoid.robot.sdk.v1.MotorControl/SetMotorVelocity',
                request_serializer=robot__sdk__pb2.MotorVelocityCommand.SerializeToString,
                response_deserializer=robot__sdk__pb2.MotorCommandReply.FromString,
                _registered_method=True)
        self.SetMotorPosition = channel.unary_unary(
                '/humanoid.robot.sdk.v1.MotorControl/SetMotorPosition',
                request_serializer=robot__sdk__pb2.MotorPositionCommand.SerializeToString,
                response_deserializer=robot__sdk__pb2.MotorCommandReply.FromString,
                _registered_method=True)
        self.SetMotorMit = channel.unary_unary(
                '/humanoid.robot.sdk.v1.MotorControl/SetMotorMit',
                request_serializer=robot__sdk__pb2.MotorMitCommand.SerializeToString,
                response_deserializer=robot__sdk__pb2.MotorCommandReply.FromString,
                _registered_method=True)
        self.GetMotorStatus = channel.unary_unary(
                '/humanoid.robot.sdk.v1.MotorControl/GetMotorStatus',
                request_serializer=robot__sdk__pb2.MotorSelection.SerializeToString,
                response_deserializer=robot__sdk__pb2.MotorStatusReply.FromString,
                _registered_method=True)


class MotorControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnableMotors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableMotors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMotorVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMotorPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMotorMit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMotorStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotorControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnableMotors': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableMotors,
                    request_deserializer=robot__sdk__pb2.MotorSelection.FromString,
                    response_serializer=robot__sdk__pb2.MotorCommandReply.SerializeToString,
            ),
            'DisableMotors': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableMotors,
                    request_deserializer=robot__sdk__pb2.MotorSelection.FromString,
                    response_serializer=robot__sdk__pb2.MotorCommandReply.SerializeToString,
            ),
            'SetMotorVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMotorVelocity,
                    request_deserializer=robot__sdk__pb2.MotorVelocityCommand.FromString,
                    response_serializer=robot__sdk__pb2.MotorCommandReply.SerializeToString,
            ),
            'SetMotorPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMotorPosition,
                    request_deserializer=robot__sdk__pb2.MotorPositionCommand.FromString,
                    response_serializer=robot__sdk__pb2.MotorCommandReply.SerializeToString,
            ),
            'SetMotorMit': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMotorMit,
                    request_deserializer=robot__sdk__pb2.MotorMitCommand.FromString,
                    response_serializer=robot__sdk__pb2.MotorCommandReply.SerializeToString,
            ),
            'GetMotorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMotorStatus,
                    request_deserializer=robot__sdk__pb2.MotorSelection.FromString,
                    response_serializer=robot__sdk__pb2.MotorStatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'humanoid.robot.sdk.v1.MotorControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('humanoid.robot.sdk.v1.MotorControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotorControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnableMotors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.MotorControl/EnableMotors',
            robot__sdk__pb2.MotorSelection.SerializeToString,
            robot__sdk__pb2.MotorCommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableMotors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.MotorControl/DisableMotors',
            robot__sdk__pb2.MotorSelection.SerializeToString,
            robot__sdk__pb2.MotorCommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMotorVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.MotorControl/SetMotorVelocity',
            robot__sdk__pb2.MotorVelocityCommand.SerializeToString,
            robot__sdk__pb2.MotorCommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMotorPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.MotorControl/SetMotorPosition',
            robot__sdk__pb2.MotorPositionCommand.SerializeToString,
            robot__sdk__pb2.MotorCommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMotorMit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.MotorControl/SetMotorMit',
            robot__sdk__pb2.MotorMitCommand.SerializeToString,
            robot__sdk__pb2.MotorCommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMotorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/humanoid.robot.sdk.v1.MotorControl/GetMotorStatus',
            robot__sdk__pb2.MotorSelection.SerializeToString,
            robot__sdk__pb2.MotorStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
